S = SceneAPI();

% Aperture stop in front
S = S.addSurface('circaper','center',[0 0 0],'axis',[1 0 0],'aperture',25);

% Front spherical surface
S = S.addSurface('sphericalSurface', ...
    'center',[10 0 0],'axis',[-1 0 0], ...
    'radius',50,'aperture',25, ...
    'indexcenter',1.50,'indexout',1.0);

% Rear aspheric surface
S = S.addSurface('asphere', ...
    'center',[12 0 0],'axis',[+1 0 0], ...
    'radius',50,'k',-1.0,'a',[1e-4 0 0], ... 
    'aperture',25, ...
    'indexcenter',1.50,'indexout',1.0);

% Sensor plane
S = S.addSensor('rectangular','size',[20 20],'distance',100);

[E, Sensor] = S.build();
